### ISSUE TITLE
ImportError: No module named data_parsing

### ISSUE THREAD

**Issue by seongkyun** [dshahrokhian/YOLO_tensorflow#1]
I tried to run this code. but kernel prints out 

I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "network/YOLO_small_tf.py", line 7, in <module>
    from data_parsing import voc_utils
ImportError: No module named data_parsing

what should i do? plz help me.

**Comment by lionelkusch** [comment]
The problem is because python don't have the directory data_parsing in the path. 
You can try to change the file "network/YOLO_small_tf.py" : Put the line 8 and 7 at the beging of the file. 

In other case, How do you run the code ? (commande line, IDE, ...) 
What is your operating system ?

**Comment by dshahrokhian** [comment]
Hi,

Can you try running `dataparsing/setup.py`? That should add the dataparsing to the lib path.

Thanks,
Dani

**Comment by seongkyun** [comment]
thx. I ran setup.py and it runs. but there is another problem.
