### ISSUE TITLE
AttributeError: 'str' object has no attribute 'copy'

### ISSUE THREAD

**Issue by seongkyun** [dshahrokhian/YOLO_tensorflow#3]
sorry buddy :)

now, I got an another problem.

I wrote 

$ python network/YOLO_small_tf.py -fromfile "person.jpg" -tofile_img "person_out.jpg"

and prints out

Traceback (most recent call last):
  File "network/YOLO_small_tf.py", line 516, in <module>
    yolo = YOLO_TF(sys.argv)
  File "network/YOLO_small_tf.py", line 67, in __init__
    self.detect_from_file(self.fromfile)
  File "network/YOLO_small_tf.py", line 242, in detect_from_file
    self.show_results(filename, self.result)
  File "network/YOLO_small_tf.py", line 300, in show_results
    img_cp = img.copy()
AttributeError: 'str' object has no attribute 'copy'

my tensorflow version is R1.0.1

help me plz.

**Comment by dshahrokhian** [comment]
Try with the new changes.

Thanks,
Dani

**Comment by seongkyun** [comment]
Thank you. It perfectly works!!

best regards, @dshahrokhian !

**Comment by seongkyun** [comment]
Thanks. 
 
It works with Images PERFECTLY.  :) 
 
Now i want to implement YOLO with video.
 
and i tried
 
$ python network/YOLO_small_tf.py -video "ped1.mp4" -tofile_vid "ped1_out.mp4"
 
but it prints out 
 
Wait for the header
Wait for the header
Wait for the header
Wait for the header
...
 
 
I think it has header problem. then which format should i use??
 
i uses *.mp4 file.
 
best regards, Han 
 
  
 
 
-----Original Message-----
