### ISSUE TITLE
Wait for the header in Video data.

### ISSUE THREAD

**Issue by seongkyun** [dshahrokhian/YOLO_tensorflow#4]
Now i want to implement YOLO with video.

and I tried

$ python network/YOLO_small_tf.py -video "ped1.mp4" -tofile_vid "ped1_out.mp4"

but it prints out 

Wait for the header
Wait for the header
Wait for the header
Wait for the header
...

I think it has header problem. Then which format should i use??

i uses *.mp4 file.

best regards, Han

**Comment by dshahrokhian** [comment]
Hi,

It seems that OpenCV is having trouble opening your file ([This](https://github.com/dshahrokhian/YOLO_tensorflow/blob/master/network/YOLO_small_tf.py#L194-L197) is what is failing in `YOLO_small_tf.y`). Try Googling for solutions to "cv2.videocapture always returns false".

Thanks,
Dani
